//! Office conversion tests — real fixtures, no mocks.
//!
//! Fixtures live in `tests/fixtures/office/` and are generated by
//! `cargo run --example gen_office_fixtures` (office_oxide `create` API,
//! IR → OOXML). Regenerate after touching the generator; keep sizes small.
//! Legacy doc/xls/ppt have no creation API — no fixtures yet (see
//! IMPLEMENTATION_PLAN_office.md Phase 0 outcome).

use std::path::PathBuf;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("office")
        .join(name)
}

fn work_dir(name: &str) -> PathBuf {
    std::env::temp_dir().join("bobine_test").join("office").join(name)
}

/// Convert via the real extension dispatcher (same path users hit).
fn convert_office(name: &str, work_name: &str) -> String {
    let work = work_dir(work_name);
    std::fs::create_dir_all(&work).expect("work dir");
    let cfg = bobine::ConverterConfig::default();
    let mut conv = bobine::HybridConverter::new(cfg, &work.join("cache"));
    conv.convert(&fixture(name), &work).expect("office convert")
}

/// Assert every needle appears in `md`, in order.
fn assert_contains_in_order(md: &str, needles: &[&str]) {
    let mut pos = 0;
    for needle in needles {
        match md[pos..].find(needle) {
            Some(off) => pos += off + needle.len(),
            None => panic!("needle {needle:?} missing after offset {pos} in:\n{md}"),
        }
    }
}

#[test]
fn office_fixtures_exist_and_are_small() {
    for name in ["basic.docx", "types.xlsx", "deck.pptx"] {
        let meta = std::fs::metadata(fixture(name)).expect("fixture present");
        assert!(meta.len() < 200 * 1024, "{name} too big: {}", meta.len());
    }
}

#[test]
fn docx_converts_with_structure_in_order() {
    let md = convert_office("basic.docx", "docx");
    assert_contains_in_order(
        &md,
        &[
            "Bobine Office Fixture",
            "Styled paragraph",
            "bold",
            "italic",
            "hyperlink",
            "alpha item",
            "first step",
            "Apples",
            "Merged across two columns",
            "A claim needing citation",
        ],
    );
}

#[test]
fn xlsx_converts_all_sheets_with_typed_cells() {
    let md = convert_office("types.xlsx", "xlsx");
    assert_contains_in_order(
        &md,
        &[
            "Data",
            "Inventory",
            "Item",
            "Apples",
            "12",
            "2024-01-01",
            "Summary",
            "Sheets",
        ],
    );
}

#[test]
fn pptx_converts_slides_in_order() {
    let md = convert_office("deck.pptx", "pptx");
    assert_contains_in_order(
        &md,
        &[
            "Title slide",
            "Bobine Deck Fixture",
            "Bullets and picture",
            "Agenda",
            "Convert",
            "Numbers",
            "Quarterly",
            "Q1",
        ],
    );
}

#[test]
fn office_convert_never_panics_on_empty_docx() {
    // Minimal one-section, zero-element .docx must convert, not panic.
    let dir = work_dir("empty");
    std::fs::create_dir_all(&dir).expect("tmp");
    let path = dir.join("empty.docx");
    let ir = office_oxide::DocumentIR {
        metadata: office_oxide::ir::Metadata {
            format: office_oxide::DocumentFormat::Docx,
            ..Default::default()
        },
        sections: vec![office_oxide::ir::Section::default()],
    };
    office_oxide::create::create_from_ir(&ir, office_oxide::DocumentFormat::Docx, &path)
        .expect("write empty docx");
    let cfg = bobine::ConverterConfig::default();
    let conv = bobine::HybridConverter::new(cfg, &dir.join("cache"));
    let _ = conv
        .convert_office(&path)
        .expect("empty docx converts");
}
