"""Type stubs for bobine — generated by pyo3-stub-gen or manual."""

from enum import Enum
from typing import Callable, List, Optional, Tuple

class RoutingMode(Enum):
    Never = "never"
    Auto = "auto"
    Surgical = "surgical"
    Always = "always"

class FormulaBackend(Enum):
    TexTeller = "tex_teller"

class ModelPrecision(Enum):
    Fp32 = "fp32"
    Fp16 = "fp16"

class ModelQuantization(Enum):
    '''Formula-recognizer weight selection.
    Fp32: exact + fastest (KV-cache decode), ~1.25 GB.
    Int8: 4x smaller memory footprint, same speed, minor typographic
    drift possible (lost mathbf bold, epsilon glyph variant).
    '''
    Fp32 = "fp32"
    Int8 = "int8"

class ConverterConfig:
    def __init__(
        self,
        extract_images: bool = True,
        append_unreferenced_images: bool = True,
        use_onnx: bool = True,
        routing_mode: RoutingMode = RoutingMode.Auto,
        _formula_backend: FormulaBackend = FormulaBackend.TexTeller,
        model_precision: ModelPrecision = ModelPrecision.Fp32,
        model_quantization: ModelQuantization = ModelQuantization.Fp32,
        render_dpi: int = 300,
        formula_dpi: int = 200,
        detect_headings: bool = True,
        convert_html_tables: bool = True,
        detect_code_blocks: bool = True,
        min_formula_math_chars: int = 5,
        formula_inline_max_width_pts: float = 220.0,
        formula_pad_pts: float = 4.0,
        formula_layout_fallback: bool = False,
        math_char_threshold: int = 30,
        scanned_text_threshold: int = 50,
        ocr_lang: str = "en",
    ) -> None: ...
    @property
    def extract_images(self) -> bool: ...
    @property
    def ocr_lang(self) -> str: ...
    @property
    def routing_mode(self) -> RoutingMode: ...
    @property
    def model_precision(self) -> ModelPrecision: ...
    @property
    def model_quantization(self) -> ModelQuantization: ...

class HybridConverter:
    def __init__(self, config: ConverterConfig, cache_dir: str) -> None: ...
    def convert(self, input: str, work_dir: str) -> str: ...
    def convert_pdf(self, path: str, work_dir: str) -> str: ...
    def recognize_formula(self, image_path: str) -> Optional[str]: ...

def convert_to_markdown(
    path: str,
    config: ConverterConfig,
    work_dir: str,
    cache_dir: str,
) -> str: ...

class ConvertedDocument:
    @property
    def md_path(self) -> str: ...
    @property
    def md_text(self) -> str: ...
    @property
    def image_dir(self) -> str: ...
    @property
    def image_count(self) -> int: ...
    @property
    def page_count(self) -> int: ...

LintCallback = Callable[[str], Optional[Tuple[bool, str]]]

def ingest_document(
    path: str,
    output_dir: str,
    config: Optional[ConverterConfig] = None,
    lint_callback: Optional[LintCallback] = None,
    should_continue: Optional[Callable[[], bool]] = None,
    on_page: Optional[Callable[[int, int], None]] = None,
) -> ConvertedDocument: ...

def convert_directory(
    source_dir: str,
    output_dir: str,
    config: Optional[ConverterConfig] = None,
    lint_callback: Optional[LintCallback] = None,
) -> List[ConvertedDocument]: ...
